=== rbergmair/PyPES/dtd/testsuite.dtd
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - TESTSUITE STRUCTURE
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT testsuite (testsuite|testcase)*>
<!ATTLIST testsuite
          id ID #IMPLIED>
          
<!ELEMENT testcase (proposition*,(valid|nonvalid)*)>
<!ATTLIST testcase
          id ID #IMPLIED>

<!ELEMENT testsuiteref EMPTY>
<!ATTLIST testsuiteref
          src CDATA #REQUIRED>

<!ELEMENT valid (ref|implication|conjunction|negation)>
<!ATTLIST valid
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>

<!ELEMENT nonvalid (ref|implication|conjunction|negation)>
<!ATTLIST nonvalid
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>

<!ELEMENT compare ((greater,smaller)|(smaller,greater))>
<!ATTLIST compare
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>
<!ELEMENT greater (ref|implication|conjunction|negation)>
<!ELEMENT smaller (ref|implication|conjunction|negation)>



<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - FORMULAE
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT implication (antecedent,consequent)>
<!ELEMENT antecedent (ref|implication|conjunction|negation)>
<!ELEMENT consequent (ref|implication|conjunction|negation)>

<!ELEMENT conjunction (conjunct)*>
<!ELEMENT conjunct (ref|implication|conjunction|negation)>

<!ELEMENT negation (ref|implication|conjunction|negation)>

<!ELEMENT ref EMPTY>
<!ATTLIST ref
          src IDREF #REQUIRED>



<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - BASIC PROPOSITIONS
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT proposition (#PCDATA|rmrsbankitem)*>
<!ATTLIST proposition
          id ID #IMPLIED>

<!ELEMENT rmrsbankitem (#PCDATA)>
<!ATTLIST rmrsbankitem id CDATA #REQUIRED>

=== rbergmair/PyPES/testdta/source/toy/toy.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite>



<testsuite id="1" name="constraint removal">

<testcase id="1.1">
	<proposition id="1.1.1">Some white dogs bark.</proposition>
	<proposition id="1.1.2">Some dogs bark.</proposition>
	<true id="1.1.a">
	  <implication>
	    <antecedent> <ref src="1.1.1"/> </antecedent>
	    <consequent> <ref src="1.1.2"/> </consequent>
	  </implication>
	</true>
	<nontrue id="1.1.b">
	  <implication>
	    <antecedent> <ref src="1.1.2"/> </antecedent>
	    <consequent> <ref src="1.1.1"/> </consequent>
	  </implication>
	</nontrue>
</testcase>

<testcase id="1.2">
	<proposition id="1.2.1">Some white cats chase some black dogs.</proposition>
	<proposition id="1.2.2">Some white cats chase some dogs.</proposition>
	<true id="1.2.a">
	  <implication>
	    <antecedent> <ref src="1.2.1"/> </antecedent>
	    <consequent> <ref src="1.2.2"/> </consequent>
	  </implication>
	</true>
	<nontrue id="1.2.b">
	  <implication>
	    <antecedent> <ref src="1.2.2"/> </antecedent>
	    <consequent> <ref src="1.2.1"/> </consequent>
	  </implication>
	</nontrue>
</testcase>

</testsuite>



<testsuite id="2" name="constraint insertion">

<testcase id="2.1">

	<proposition id="2.1.1">Some dogs bark.</proposition>
	<proposition id="2.1.2">Some brown dogs bark.</proposition>
	<proposition id="2.1.3">Some big brown dogs bark.</proposition>
	
	<compare id="2.1.c">
	  <greater>
		  <implication>
		    <antecedent> <ref src="2.1.1"/> </antecedent>
		    <consequent> <ref src="2.1.2"/> </consequent>
		  </implication>
	  </greater>
	  <smaller>
		  <implication>
		    <antecedent> <ref src="2.1.1"/> </antecedent>
		    <consequent> <ref src="2.1.3"/> </consequent>
		  </implication>
	  </smaller>
	</compare>
	
</testcase>

</testsuite>



<testsuite id="3" name="predicate-argument structure">

<testcase id="3.1">
	<proposition id="3.1.1">Some white cats chase some black dogs.</proposition>
	<proposition id="3.1.2">Some white dogs chase some black cats.</proposition>
	<nontrue id="3.1.a">
	  <implication>
	    <antecedent> <ref src="3.1.1"/> </antecedent>
	    <consequent> <ref src="3.1.2"/> </consequent>
	  </implication>
	</nontrue>
	<nontrue id="3.1.b">
	  <implication>
	    <antecedent> <ref src="3.1.2"/> </antecedent>
	    <consequent> <ref src="3.1.1"/> </consequent>
	  </implication>
	</nontrue>
</testcase>

<testcase id="3.2">
	<proposition id="3.2.1">Some white cats chase some black dogs.</proposition>
	<proposition id="3.2.2">Some black cats chase some white dogs.</proposition>
	<nontrue id="3.2.a">
	  <implication>
	    <antecedent> <ref src="3.2.1"/> </antecedent>
	    <consequent> <ref src="3.2.2"/> </consequent>
	  </implication>
	</nontrue>
	<nontrue id="3.2.b">
	  <implication>
	    <antecedent> <ref src="3.2.2"/> </antecedent>
	    <consequent> <ref src="3.2.1"/> </consequent>
	  </implication>
	</nontrue>
</testcase>

<testcase id="3.3">
	<proposition id="3.3.1">Some white cats chase some black dogs.</proposition>
	<proposition id="3.3.2">Some black dogs chase some white cats.</proposition>
	<nontrue id="3.3.a">
	  <implication>
	    <antecedent> <ref src="3.3.1"/> </antecedent>
	    <consequent> <ref src="3.3.2"/> </consequent>
	  </implication>
	</nontrue>
	<nontrue id="3.3.b">
	  <implication>
	    <antecedent> <ref src="3.3.2"/> </antecedent>
	    <consequent> <ref src="3.3.1"/> </consequent>
	  </implication>
	</nontrue>
</testcase>

</testsuite>



<testsuite id="4" name="quantifier strength">

<testcase id="4.1">
	<proposition id="4.1.1">All white cats chase some black dogs.</proposition>
	<proposition id="4.1.2">Some white cats chase some black dogs.</proposition>
	<true id="4.1.a">
	  <implication>
	    <antecedent> <ref src="4.1.1"/> </antecedent>
	    <consequent> <ref src="4.1.2"/> </consequent>
	  </implication>
	</true>
	<nontrue id="4.1.b" ignore="yes">
	  <implication>
	    <antecedent> <ref src="4.1.2"/> </antecedent>
	    <consequent> <ref src="4.1.1"/> </consequent>
	  </implication>
	</nontrue>
</testcase>

<testcase id="4.2">
	<proposition id="4.2.1">All white cats chase all black dogs.</proposition>
	<proposition id="4.2.2">All white cats chase some black dogs.</proposition>
	<true id="4.2.a">
	  <implication>
	    <antecedent> <ref src="4.2.1"/> </antecedent>
	    <consequent> <ref src="4.2.2"/> </consequent>
	  </implication>
	</true>
	<nontrue id="4.2.b" ignore="yes">
	  <implication>
	    <antecedent> <ref src="4.2.2"/> </antecedent>
	    <consequent> <ref src="4.2.1"/> </consequent>
	  </implication>
	</nontrue>
</testcase>

</testsuite>



</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-5-3.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="5.3" name="opposites">

<testcase id="3.204">
  <proposition id="3.204.1">
    <rmrsbankitem id="40">Mickey is a small animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.204.2">
    <rmrsbankitem id="41">Is Mickey a large animal?</rmrsbankitem>
  </proposition>
  <valid id="3.204.a">
    <theory> <ref src="3.204.1"/> </theory>
    <conclusion> <negation> <ref src="3.204.2"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.205">
  <proposition id="3.205.1">
    <rmrsbankitem id="42">Dumbo is a large animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.205.2">
    <rmrsbankitem id="43">Is Dumbo a small animal?</rmrsbankitem>
  </proposition>
  <valid id="3.205.a">
    <theory> <ref src="3.205.1"/> </theory>
    <conclusion> <negation> <ref src="3.205.2"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.206">
  <proposition id="3.206.1">
    <rmrsbankitem id="96">Fido is not a small animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.206.2">
    <rmrsbankitem id="44">Is Fido a large animal?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.206.a">
    <theory> <ref src="3.206.1"/> </theory>
    <conclusion> <ref src="3.206.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.206.b">
    <theory> <ref src="3.206.1"/> </theory>
    <conclusion> <negation> <ref src="3.206.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.207">
  <proposition id="3.207.1">
    <rmrsbankitem id="97">Fido is not a large animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.207.2">
    <rmrsbankitem id="45">Is Fido a small animal?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.207.a">
    <theory> <ref src="3.207.1"/> </theory>
    <conclusion> <ref src="3.207.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.207.b">
    <theory> <ref src="3.207.1"/> </theory>
    <conclusion> <negation> <ref src="3.207.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.208">
  <proposition id="3.208.1">
    <rmrsbankitem id="40">Mickey is a small animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.208.2">
    <rmrsbankitem id="42">Dumbo is a large animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.208.3">
    <rmrsbankitem id="46">Is Mickey smaller than Dumbo?</rmrsbankitem>
  </proposition>
  <valid id="3.208.a">
    <theory> <ref src="3.208.1"/> <ref src="3.208.2"/> </theory>
    <conclusion> <ref src="3.208.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.209">
  <proposition id="3.209.1">
    <rmrsbankitem id="40">Mickey is a small animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.209.2">
    <rmrsbankitem id="42">Dumbo is a large animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.209.3">
    <rmrsbankitem id="47">Is Mickey larger than Dumbo?</rmrsbankitem>
  </proposition>
  <valid id="3.209.a">
    <theory> <ref src="3.209.1"/> <ref src="3.209.2"/> </theory>
    <conclusion> <negation> <ref src="3.209.3"/> </negation> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-5-4.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="5.4" name="extensional comparison classes">

<testcase id="3.210">
  <proposition id="3.210.1">
    <rmrsbankitem id="48">All mice are small animals.</rmrsbankitem>
  </proposition>
  <proposition id="3.210.2">
    <rmrsbankitem id="49">Mickey is a large mouse.</rmrsbankitem>
  </proposition>
  <proposition id="3.210.3">
    <rmrsbankitem id="41">Is Mickey a large animal?</rmrsbankitem>
  </proposition>
  <valid id="3.210.a">
    <theory> <ref src="3.210.1"/> <ref src="3.210.2"/> </theory>
    <conclusion> <negation> <ref src="3.210.3"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.211">
  <proposition id="3.211.1">
    <rmrsbankitem id="50">All elephants are large animals.</rmrsbankitem>
  </proposition>
  <proposition id="3.211.2">
    <rmrsbankitem id="51">Dumbo is a small elephant.</rmrsbankitem>
  </proposition>
  <proposition id="3.211.3">
    <rmrsbankitem id="43">Is Dumbo a small animal?</rmrsbankitem>
  </proposition>
  <valid id="3.211.a">
    <theory> <ref src="3.211.1"/> <ref src="3.211.2"/> </theory>
    <conclusion> <negation> <ref src="3.211.3"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.212">
  <proposition id="3.212.1">
    <rmrsbankitem id="48">All mice are small animals.</rmrsbankitem>
  </proposition>
  <proposition id="3.212.2">
    <rmrsbankitem id="50">All elephants are large animals.</rmrsbankitem>
  </proposition>
  <proposition id="3.212.3">
    <rmrsbankitem id="49">Mickey is a large mouse.</rmrsbankitem>
  </proposition>
  <proposition id="3.212.4">
    <rmrsbankitem id="51">Dumbo is a small elephant.</rmrsbankitem>
  </proposition>
  <proposition id="3.212.5">
    <rmrsbankitem id="52">Is Dumbo larger than Mickey?</rmrsbankitem>
  </proposition>
  <valid id="3.212.a">
    <theory> <ref src="3.212.1"/> <ref src="3.212.2"/> <ref src="3.212.3"/> <ref src="3.212.4"/> </theory>
    <conclusion> <ref src="3.212.5"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.213">
  <proposition id="3.213.1">
    <rmrsbankitem id="48">All mice are small animals.</rmrsbankitem>
  </proposition>
  <proposition id="3.213.2">
    <rmrsbankitem id="49">Mickey is a large mouse.</rmrsbankitem>
  </proposition>
  <proposition id="3.213.3">
    <rmrsbankitem id="3">Is Mickey small?</rmrsbankitem>
  </proposition>
  <!-- ??? -->
  <nonvalid id="3.213.a">
    <theory> <ref src="3.213.1"/> <ref src="3.213.2"/> </theory>
    <conclusion> <ref src="3.213.3"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.213.b">
    <theory> <ref src="3.213.1"/> <ref src="3.213.2"/> </theory>
    <conclusion> <negation> <ref src="3.213.3"/> </negation> </conclusion>
  </nonvalid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-6-2.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="6.2" name="clausal complement">

<testcase id="3.239">
  <proposition id="3.239.1">
    <rmrsbankitem id="163">ITEL won more orders than APCOM lost.</rmrsbankitem>
  </proposition>
  <proposition id="3.239.2">
    <rmrsbankitem id="57">Did ITEL win some orders?</rmrsbankitem>
  </proposition>
  <!-- ??? -->
  <valid id="3.239.a">
    <theory> <ref src="3.239.1"/> </theory>
    <conclusion> <ref src="3.239.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.240">
  <proposition id="3.240.1">
    <rmrsbankitem id="163">ITEL won more orders than APCOM lost.</rmrsbankitem>
  </proposition>
  <proposition id="3.240.2">
    <rmrsbankitem id="60">Did APCOM lose some orders?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.240.a">
    <theory> <ref src="3.240.1"/> </theory>
    <conclusion> <ref src="3.240.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.240.a">
    <theory> <ref src="3.240.1"/> </theory>
    <conclusion> <negation> <ref src="3.240.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.241">
  <proposition id="3.241.1">
    <rmrsbankitem id="163">ITEL won more orders than APCOM lost.</rmrsbankitem>
  </proposition>
  <proposition id="3.241.2">
    <rmrsbankitem id="17">APCOM lost ten orders.</rmrsbankitem>
  </proposition>
  <proposition id="3.241.3">
    <rmrsbankitem id="161">Did ITEL win at least eleven orders?</rmrsbankitem>
  </proposition>
  <valid id="3.241.a">
    <theory> <ref src="3.241.1"/> <ref src="3.241.2"/> </theory>
    <conclusion> <ref src="3.241.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>
