=== rbergmair/PyPES/dtd/testsuite.dtd
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - TESTSUITE STRUCTURE
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT testsuite (testsuite|testcase)*>
<!ATTLIST testsuite
          id ID #IMPLIED>
          
<!ELEMENT testcase (proposition*,(valid|nonvalid)*)>
<!ATTLIST testcase
          id ID #IMPLIED>

<!ELEMENT testsuiteref EMPTY>
<!ATTLIST testsuiteref
          src CDATA #REQUIRED>

<!ELEMENT valid (ref|implication|conjunction|negation)>
<!ATTLIST valid
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>

<!ELEMENT nonvalid (ref|implication|conjunction|negation)>
<!ATTLIST nonvalid
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>

<!ELEMENT compare ((greater,smaller)|(smaller,greater))>
<!ATTLIST compare
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>
<!ELEMENT greater (ref|implication|conjunction|negation)>
<!ELEMENT smaller (ref|implication|conjunction|negation)>



<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - FORMULAE
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT implication (antecedent,consequent)>
<!ELEMENT antecedent (ref|implication|conjunction|negation)>
<!ELEMENT consequent (ref|implication|conjunction|negation)>

<!ELEMENT conjunction (conjunct)*>
<!ELEMENT conjunct (ref|implication|conjunction|negation)>

<!ELEMENT negation (ref|implication|conjunction|negation)>

<!ELEMENT ref EMPTY>
<!ATTLIST ref
          src IDREF #REQUIRED>



<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - BASIC PROPOSITIONS
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT proposition (#PCDATA|rmrsbankitem)*>
<!ATTLIST proposition
          id ID #IMPLIED>

<!ELEMENT rmrsbankitem (#PCDATA)>
<!ATTLIST rmrsbankitem id CDATA #REQUIRED>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-6-3.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="6.3" name="measure phrases">

<testcase id="3.242">
  <proposition id="3.242.1">
    <rmrsbankitem id="164">The PC-6082 is faster than 500 MIPS.</rmrsbankitem>
  </proposition>
  <proposition id="3.242.2">
    <rmrsbankitem id="165">The ITEL-ZX is slower than 500 MIPS.</rmrsbankitem>
  </proposition>
  <proposition id="3.242.3">
    <rmrsbankitem id="166">Is the PC-6082 faster than the ITEL-ZX?</rmrsbankitem>
  </proposition>
  <valid id="3.242.a">
    <theory> <ref src="3.242.1"/> <ref src="3.242.2"/> </theory>
    <conclusion> <ref src="3.242.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-5-2.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="5.2" name="no comparison class">

<testcase id="3.202">
  <proposition id="3.202.1">
    <rmrsbankitem id="38">Every mammal is an animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.202.2">
    <rmrsbankitem id="154">Is every four-legged mammal a four-legged animal?</rmrsbankitem>
  </proposition>
  <valid id="3.202.a">
    <theory> <ref src="3.202.1"/> </theory>
    <conclusion> <ref src="3.202.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.203">
  <proposition id="3.203.1">
    <rmrsbankitem id="39">Dumbo is a four-legged animal.</rmrsbankitem>
  </proposition>
  <proposition id="3.203.2">
    <rmrsbankitem id="2">Is Dumbo four-legged?</rmrsbankitem>
  </proposition>
  <valid id="3.203.a">
    <theory> <ref src="3.203.1"/> </theory>
    <conclusion> <ref src="3.203.2"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-6-4.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="6.4" name="differential comparatives">

<testcase id="3.243">
  <proposition id="3.243.1">
    <rmrsbankitem id="167">ITEL sold 3000 more computers than APCOM.</rmrsbankitem>
  </proposition>
  <proposition id="3.243.2">
    <rmrsbankitem id="61">APCOM sold exactly 2500 computers.</rmrsbankitem>
  </proposition>
  <proposition id="3.243.3">
    <rmrsbankitem id="62">Did ITEL sell 5500 computers?</rmrsbankitem>
  </proposition>
  <valid id="3.243.a">
    <theory> <ref src="3.243.1"/> <ref src="3.243.2"/> </theory>
    <conclusion> <ref src="3.243.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-8-2.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="8.2" name="distributive and collective predication">

<testcase id="3.331">
  <proposition id="3.331.1">
    <rmrsbankitem id="105">Smith and Jones left the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.331.2">
    <rmrsbankitem id="64">Did Smith leave the meeting?</rmrsbankitem>
  </proposition>
  <valid id="3.331.a">
    <theory> <ref src="3.331.1"/> </theory>
    <conclusion> <ref src="3.331.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.332">
  <proposition id="3.332.1">
    <rmrsbankitem id="105">Smith and Jones left the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.332.2">
    <rmrsbankitem id="65">Did Jones leave the meeting?</rmrsbankitem>
  </proposition>
  <valid id="3.332.a">
    <theory> <ref src="3.332.1"/> </theory>
    <conclusion> <ref src="3.332.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.333">
  <proposition id="3.333.1">
    <rmrsbankitem id="66">Smith, Anderson and Jones met.</rmrsbankitem>
  </proposition>
  <proposition id="3.333.2">
    <rmrsbankitem id="217">Was there a group of people that met?</rmrsbankitem>
  </proposition>
  <valid id="3.333.a">
    <theory> <ref src="3.333.1"/> </theory>
    <conclusion> <ref src="3.333.2"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/source/fracas/fracas-5-4.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="5.4" name="extensional comparison classes">

<testcase id="3.210">
  <proposition id="3.210.1">
    All mice are small animals.
  </proposition>
  <proposition id="3.210.2">
    Mickey is a large mouse.
  </proposition>
  <proposition id="3.210.3">
    Is Mickey a large animal?
  </proposition>
  <valid id="3.210.a">
    <theory> <ref src="3.210.1"/> <ref src="3.210.2"/> </theory>
    <conclusion> <negation> <ref src="3.210.3"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.211">
  <proposition id="3.211.1">
    All elephants are large animals.
  </proposition>
  <proposition id="3.211.2">
    Dumbo is a small elephant.
  </proposition>
  <proposition id="3.211.3">
    Is Dumbo a small animal?
  </proposition>
  <valid id="3.211.a">
    <theory> <ref src="3.211.1"/> <ref src="3.211.2"/> </theory>
    <conclusion> <negation> <ref src="3.211.3"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.212">
  <proposition id="3.212.1">
    All mice are small animals.
  </proposition>
  <proposition id="3.212.2">
    All elephants are large animals.
  </proposition>
  <proposition id="3.212.3">
    Mickey is a large mouse.
  </proposition>
  <proposition id="3.212.4">
    Dumbo is a small elephant.
  </proposition>
  <proposition id="3.212.5">
    Is Dumbo larger than Mickey?
  </proposition>
  <valid id="3.212.a">
    <theory> <ref src="3.212.1"/> <ref src="3.212.2"/> <ref src="3.212.3"/> <ref src="3.212.4"/> </theory>
    <conclusion> <ref src="3.212.5"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.213">
  <proposition id="3.213.1">
    All mice are small animals.
  </proposition>
  <proposition id="3.213.2">
    Mickey is a large mouse.
  </proposition>
  <proposition id="3.213.3">
    Is Mickey small?
  </proposition>
  <!-- ??? -->
  <nonvalid id="3.213.a">
    <theory> <ref src="3.213.1"/> <ref src="3.213.2"/> </theory>
    <conclusion> <ref src="3.213.3"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.213.b">
    <theory> <ref src="3.213.1"/> <ref src="3.213.2"/> </theory>
    <conclusion> <negation> <ref src="3.213.3"/> </negation> </conclusion>
  </nonvalid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-9-2.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="9.2" name="preceptive attitudes: see with bare infinitive complements">

  <testsuite id="9.2.1" name="inferences we do not get">

    <testcase id="3.340">
      <proposition id="3.340.1">
        <rmrsbankitem id="106">Smith saw Jones sign the contract.</rmrsbankitem>
      </proposition>
      <proposition id="3.340.2">
        <rmrsbankitem id="247">If Jones signed the contract, his heart was beating.</rmrsbankitem>
      </proposition>
      <proposition id="3.340.3">
        <rmrsbankitem id="107">Did Smith see Jones' heart beat?</rmrsbankitem>
      </proposition>
      <nonvalid id="3.340.a">
        <theory> <ref src="3.340.1"/> <ref src="3.340.2"/> </theory>
        <conclusion> <ref src="3.340.3"/> </conclusion>
      </nonvalid>
      <nonvalid id="3.340.b">
        <theory> <ref src="3.340.1"/> <ref src="3.340.2"/> </theory>
        <conclusion> <negation> <ref src="3.340.3"/> </negation> </conclusion>
      </nonvalid>
    </testcase>

    <testcase id="3.341">
      <proposition id="3.341.1">
        <rmrsbankitem id="106">Smith saw Jones sign the contract.</rmrsbankitem>
      </proposition>
      <proposition id="3.341.2">
        <rmrsbankitem id="248">When Jones signed the contract, his heart was beating.</rmrsbankitem>
      </proposition>
      <proposition id="3.341.3">
        <rmrsbankitem id="107">Did Smith see Jones' heart beat?</rmrsbankitem>
      </proposition>
      <nonvalid id="3.341.a">
        <theory> <ref src="3.341.1"/> <ref src="3.341.2"/> </theory>
        <conclusion> <ref src="3.341.3"/> </conclusion>
      </nonvalid>
      <nonvalid id="3.341.b">
        <theory> <ref src="3.341.1"/> <ref src="3.341.2"/> </theory>
        <conclusion> <negation> <ref src="3.341.3"/> </negation> </conclusion>
      </nonvalid>
    </testcase>

  </testsuite>

  <testsuite id="9.2.2" name="verdicality">

    <testcase id="3.342">
      <proposition id="3.342.1">
        <rmrsbankitem id="106">Smith saw Jones sign the contract.</rmrsbankitem>
      </proposition>
      <proposition id="3.342.2">
        <rmrsbankitem id="32">Did Jones sign the contract?</rmrsbankitem>
      </proposition>
      <valid id="3.342.a">
        <theory> <ref src="3.342.1"/> </theory>
        <conclusion> <ref src="3.342.2"/> </conclusion>
      </valid>
    </testcase>

  </testsuite>

  <testsuite id="9.2.3" name="substitution">

    <testcase id="3.343">
      <proposition id="3.343.1">
        <rmrsbankitem id="106">Smith saw Jones sign the contract.</rmrsbankitem>
      </proposition>
      <proposition id="3.343.2">
        <rmrsbankitem id="108">Jones is the chairman of ITEL.</rmrsbankitem>
      </proposition>
      <proposition id="3.343.3">
        <rmrsbankitem id="285">Did Smith see the chairman of ITEL sign the contract?</rmrsbankitem>
      </proposition>
      <valid id="3.343.a">
        <theory> <ref src="3.343.1"/> <ref src="3.343.2"/> </theory>
        <conclusion> <ref src="3.343.3"/> </conclusion>
      </valid>
    </testcase>

  </testsuite>

  <testsuite id="9.2.4" name="existential instantiation">

    <testcase id="3.344">
      <proposition id="3.344.1">
        <rmrsbankitem id="286">Helen saw the chairman of the department answer the phone.</rmrsbankitem>
      </proposition>
      <proposition id="3.344.2">
        <rmrsbankitem id="221">The chairman of the department is a person.</rmrsbankitem>
      </proposition>
      <proposition id="3.344.3">
        <rmrsbankitem id="249">Is there anyone whom Helen saw answer the phone?</rmrsbankitem>
      </proposition>
      <valid id="3.344.a">
        <theory> <ref src="3.344.1"/> <ref src="3.344.2"/> </theory>
        <conclusion> <ref src="3.344.3"/> </conclusion>
      </valid>
    </testcase>

  </testsuite>

  <testsuite id="9.2.5" name="conjunction distribution">

    <testcase id="3.345">
      <!-- Smith saw Jones sign the contract and his secretary make a copy. -->
      <proposition id="3.345.1">
        <rmrsbankitem id="318">Smith saw Jones sign the contract and saw his secretary make a copy.</rmrsbankitem>
      </proposition>
      <proposition id="3.345.2">
        <rmrsbankitem id="171">Did Smith see Jones sign the contract?</rmrsbankitem>
      </proposition>
      <valid id="3.345.a">
        <theory> <ref src="3.345.1"/> </theory>
        <conclusion> <ref src="3.345.2"/> </conclusion>
      </valid>
    </testcase>

  </testsuite>

  <testsuite id="9.2.6" name="disjunction distribution">

    <testcase id="3.346">
      <proposition id="3.346.1">
        <rmrsbankitem id="314">Smith saw Jones sign the contract or cross out the crucial clause.</rmrsbankitem>
      </proposition>
      <!--
        Did Smith either see Jones sign the contract or
          see Jones cross out the crucial clause?
      -->
      <proposition id="3.346.2">
        <rmrsbankitem id="324">Did Smith see Jones sign the contract or see Jones cross out the crucial clause?</rmrsbankitem>
      </proposition>
      <valid id="3.346.a">
        <theory> <ref src="3.346.1"/> </theory>
        <conclusion> <ref src="3.346.2"/> </conclusion>
      </valid>
    </testcase>

  </testsuite>

</testsuite>

=== rbergmair/PyPES/testdta/source/fracas/fracas-2-6.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="2.6" name="collective and distributive plurals">

<testcase id="3.111">
  <proposition id="3.111.1">
    Smith signed one contract.
  </proposition>
  <proposition id="3.111.2">
    Jones signed another contract.
  </proposition>
  <proposition id="3.111.3">
    Did Smith and Jones sign two contracts?
  </proposition>
  <valid id="3.111.a">
    <theory> <ref src="3.111.1"/> <ref src="3.111.2"/> </theory>
    <conclusion> <ref src="3.111.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.112">
  <proposition id="3.112.1">
    Smith signed two contracts.
  </proposition>
  <proposition id="3.112.2">
    Jones signed two contracts.
  </proposition>
  <proposition id="3.112.3">
    Did Smith and Jones sign two contracts?
  </proposition>
  <valid id="3.112.a">
    <theory> <ref src="3.112.1"/> <ref src="3.112.2"/> </theory>
    <conclusion> <ref src="3.112.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.113">
  <proposition id="3.113.1">
    Smith signed two contracts.
  </proposition>
  <proposition id="3.113.2">
    Jones also signed them.
  </proposition>
  <proposition id="3.113.3">
    Did Smith and Jones sign two contracts?
  </proposition>
  <valid id="3.113.a">
    <theory> <ref src="3.113.1"/> <ref src="3.113.2"/> </theory>
    <conclusion> <ref src="3.113.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-2-5.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="2.5" name="negated plurals">

<testcase id="3.105">
  <proposition id="3.105.1">
    <rmrsbankitem id="88">Just one accountant attended the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.105.2">
    <rmrsbankitem id="89">Did no accountants attend the meeting?</rmrsbankitem>
  </proposition>
  <valid id="3.105.a">
    <theory> <ref src="3.105.1"/> </theory>
    <conclusion> <negation> <ref src="3.105.2"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.106">
  <proposition id="3.106.1">
    <rmrsbankitem id="88">Just one accountant attended the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.106.2">
    <rmrsbankitem id="90">Did no accountant attend the meeting?</rmrsbankitem>
  </proposition>
  <valid id="3.106.a">
    <theory> <ref src="3.106.1"/> </theory>
    <conclusion> <negation> <ref src="3.106.2"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.107">
  <proposition id="3.107.1">
    <rmrsbankitem id="88">Just one accountant attended the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.107.2">
    <rmrsbankitem id="91">Did any accountants attend the meeting?</rmrsbankitem>
  </proposition>
  <valid id="3.107.a">
    <theory> <ref src="3.107.1"/> </theory>
    <conclusion> <ref src="3.107.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.108">
  <proposition id="3.108.1">
    <rmrsbankitem id="88">Just one accountant attended the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.108.2">
    <rmrsbankitem id="92">Did any accountant attend the meeting?</rmrsbankitem>
  </proposition>
  <valid id="3.108.a">
    <theory> <ref src="3.108.1"/> </theory>
    <conclusion> <ref src="3.108.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.109">
  <proposition id="3.109.1">
    <rmrsbankitem id="88">Just one accountant attended the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.109.2">
    <rmrsbankitem id="93">Did some accountants attend the meeting?</rmrsbankitem>
  </proposition>
  <!-- ??? -->
  <valid id="3.109.a">
    <theory> <ref src="3.109.1"/> </theory>
    <conclusion> <negation> <ref src="3.109.2"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.110">
  <proposition id="3.110.1">
    <rmrsbankitem id="88">Just one accountant attended the meeting.</rmrsbankitem>
  </proposition>
  <proposition id="3.110.2">
    <rmrsbankitem id="94">Did some accountant attend the meeting?</rmrsbankitem>
  </proposition>
  <valid id="3.110.a">
    <theory> <ref src="3.110.1"/> </theory>
    <conclusion> <ref src="3.110.2"/> </conclusion>
  </valid>
</testcase>

</testsuite>
