=== rbergmair/PyPES/dtd/testsuite.dtd
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - TESTSUITE STRUCTURE
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT testsuite (testsuite|testcase)*>
<!ATTLIST testsuite
          id ID #IMPLIED>
          
<!ELEMENT testcase (proposition*,(valid|nonvalid)*)>
<!ATTLIST testcase
          id ID #IMPLIED>

<!ELEMENT testsuiteref EMPTY>
<!ATTLIST testsuiteref
          src CDATA #REQUIRED>

<!ELEMENT valid (ref|implication|conjunction|negation)>
<!ATTLIST valid
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>

<!ELEMENT nonvalid (ref|implication|conjunction|negation)>
<!ATTLIST nonvalid
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>

<!ELEMENT compare ((greater,smaller)|(smaller,greater))>
<!ATTLIST compare
          id ID #IMPLIED
          ignore (yes|no) #IMPLIED>
<!ELEMENT greater (ref|implication|conjunction|negation)>
<!ELEMENT smaller (ref|implication|conjunction|negation)>



<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - FORMULAE
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT implication (antecedent,consequent)>
<!ELEMENT antecedent (ref|implication|conjunction|negation)>
<!ELEMENT consequent (ref|implication|conjunction|negation)>

<!ELEMENT conjunction (conjunct)*>
<!ELEMENT conjunct (ref|implication|conjunction|negation)>

<!ELEMENT negation (ref|implication|conjunction|negation)>

<!ELEMENT ref EMPTY>
<!ATTLIST ref
          src IDREF #REQUIRED>



<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   - BASIC PROPOSITIONS
   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT proposition (#PCDATA|rmrsbankitem)*>
<!ATTLIST proposition
          id ID #IMPLIED>

<!ELEMENT rmrsbankitem (#PCDATA)>
<!ATTLIST rmrsbankitem id CDATA #REQUIRED>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-2-4.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="2.4" name="dependent plurals">

<testcase id="3.103">
  <proposition id="3.103.1">
    <rmrsbankitem id="86">All APCOM managers have company cars.</rmrsbankitem>
  </proposition>
  <proposition id="3.103.2">
    <rmrsbankitem id="34">Jones is an APCOM manager.</rmrsbankitem>
  </proposition>
  <proposition id="3.103.3">
    <rmrsbankitem id="87">Does Jones have a company car?</rmrsbankitem>
  </proposition>
  <valid id="3.103.a">
    <theory> <ref src="3.103.1"/> <ref src="3.103.2"/> </theory>
    <conclusion> <ref src="3.103.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.104">
  <proposition id="3.104.1">
    <rmrsbankitem id="86">All APCOM managers have company cars.</rmrsbankitem>
  </proposition>
  <proposition id="3.104.2">
    <rmrsbankitem id="34">Jones is an APCOM manager.</rmrsbankitem>
  </proposition>
  <proposition id="3.104.3">
    <rmrsbankitem id="206">Does Jones have more than one company car?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.104.a">
    <theory> <ref src="3.104.1"/> <ref src="3.104.2"/> </theory>
    <conclusion> <ref src="3.104.3"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.104.b">
    <theory> <ref src="3.104.1"/> <ref src="3.104.2"/> </theory>
    <conclusion> <negation> <ref src="3.104.3"/> </negation> </conclusion>
  </nonvalid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/source/fracas/fracas-6-4.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="6.4" name="differential comparatives">

<testcase id="3.243">
  <proposition id="3.243.1">
    ITEL sold 3000 more computers than APCOM.
  </proposition>
  <proposition id="3.243.2">
    APCOM sold exactly 2500 computers.
  </proposition>
  <proposition id="3.243.3">
    Did ITEL sell 5500 computers?
  </proposition>
  <valid id="3.243.a">
    <theory> <ref src="3.243.1"/> <ref src="3.243.2"/> </theory>
    <conclusion> <ref src="3.243.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/source/fracas/fracas-6-3.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="6.3" name="measure phrases">

<testcase id="3.242">
  <proposition id="3.242.1">
    The PC-6082 is faster than 500 MIPS.
  </proposition>
  <proposition id="3.242.2">
    The ITEL-ZX is slower than 500 MIPS.
  </proposition>
  <proposition id="3.242.3">
    Is the PC-6082 faster than the ITEL-ZX?
  </proposition>
  <valid id="3.242.a">
    <theory> <ref src="3.242.1"/> <ref src="3.242.2"/> </theory>
    <conclusion> <ref src="3.242.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-6-1.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="6.1" name="phrasal comparatives">

<testcase id="3.220">
  <proposition id="3.220.1">
    <rmrsbankitem id="157">The PC-6082 is faster than the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.220.2">
    <rmrsbankitem id="11">The ITEL-XZ is fast.</rmrsbankitem>
  </proposition>
  <proposition id="3.220.3">
    <rmrsbankitem id="12">Is the PC-6082 fast?</rmrsbankitem>
  </proposition>
  <valid id="3.220.a">
    <theory> <ref src="3.220.1"/> <ref src="3.220.2"/> </theory>
    <conclusion> <ref src="3.220.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.221">
  <proposition id="3.221.1">
    <rmrsbankitem id="157">The PC-6082 is faster than the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.221.2">
    <rmrsbankitem id="12">Is the PC-6082 fast?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.221.a">
    <theory> <ref src="3.221.1"/> </theory>
    <conclusion> <ref src="3.221.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.221.b">
    <theory> <ref src="3.221.1"/> </theory>
    <conclusion> <negation> <ref src="3.221.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.222">
  <proposition id="3.222.1">
    <rmrsbankitem id="157">The PC-6082 is faster than the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.222.2">
    <rmrsbankitem id="13">The PC-6082 is fast.</rmrsbankitem>
  </proposition>
  <proposition id="3.222.3">
    <rmrsbankitem id="14">Is the ITEL-XZ fast?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.222.a">
    <theory> <ref src="3.222.1"/> <ref src="3.222.2"/> </theory>
    <conclusion> <ref src="3.222.3"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.222.b">
    <theory> <ref src="3.222.1"/> <ref src="3.222.2"/> </theory>
    <conclusion> <negation> <ref src="3.222.3"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.223">
  <proposition id="3.223.1">
    <rmrsbankitem id="157">The PC-6082 is faster than the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.223.2">
    <rmrsbankitem id="15">The PC-6082 is slow.</rmrsbankitem>
  </proposition>
  <proposition id="3.223.3">
    <rmrsbankitem id="14">Is the ITEL-XZ fast?</rmrsbankitem>
  </proposition>
  <valid id="3.223.a">
    <theory> <ref src="3.223.1"/> <ref src="3.223.2"/> </theory>
    <conclusion> <negation> <ref src="3.223.3"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.224">
  <proposition id="3.224.1">
    <rmrsbankitem id="209">The PC-6082 is as fast as the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.224.2">
    <rmrsbankitem id="11">The ITEL-XZ is fast.</rmrsbankitem>
  </proposition>
  <proposition id="3.224.3">
    <rmrsbankitem id="12">Is the PC-6082 fast?</rmrsbankitem>
  </proposition>
  <valid id="3.224.a">
    <theory> <ref src="3.224.1"/> <ref src="3.224.2"/> </theory>
    <conclusion> <ref src="3.224.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.225">
  <proposition id="3.225.1">
    <rmrsbankitem id="209">The PC-6082 is as fast as the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.225.2">
    <rmrsbankitem id="12">Is the PC-6082 fast?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.225.a">
    <theory> <ref src="3.225.1"/> </theory>
    <conclusion> <ref src="3.225.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.225.b">
    <theory> <ref src="3.225.1"/> </theory>
    <conclusion> <negation> <ref src="3.225.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.226">
  <proposition id="3.226.1">
    <rmrsbankitem id="209">The PC-6082 is as fast as the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.226.2">
    <rmrsbankitem id="13">The PC-6082 is fast.</rmrsbankitem>
  </proposition>
  <proposition id="3.226.3">
    <rmrsbankitem id="14">Is the ITEL-XZ fast?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.226.a">
    <theory> <ref src="3.226.1"/> <ref src="3.226.2"/> </theory>
    <conclusion> <ref src="3.226.3"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.226.a">
    <theory> <ref src="3.226.1"/> <ref src="3.226.2"/> </theory>
    <conclusion> <negation> <ref src="3.226.3"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.227">
  <proposition id="3.227.1">
    <rmrsbankitem id="209">The PC-6082 is as fast as the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.227.2">
    <rmrsbankitem id="15">The PC-6082 is slow.</rmrsbankitem>
  </proposition>
  <proposition id="3.227.3">
    <rmrsbankitem id="14">Is the ITEL-XZ fast?</rmrsbankitem>
  </proposition>
  <valid id="3.227.a">
    <theory> <ref src="3.227.1"/> <ref src="3.227.2"/> </theory>
    <conclusion> <negation> <ref src="3.227.3"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.228">
  <proposition id="3.228.1">
    <rmrsbankitem id="209">The PC-6082 is as fast as the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.228.2">
    <rmrsbankitem id="158">Is the PC-6082 faster than the ITEL-XZ?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.228.a">
    <theory> <ref src="3.228.1"/> </theory>
    <conclusion> <ref src="3.228.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.228.b">
    <theory> <ref src="3.228.1"/> </theory>
    <conclusion> <negation> <ref src="3.228.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.229">
  <proposition id="3.229.1">
    <rmrsbankitem id="209">The PC-6082 is as fast as the ITEL-XZ.</rmrsbankitem>
  </proposition>
  <proposition id="3.229.2">
    <rmrsbankitem id="159">Is the PC-6082 slower than the ITEL-XZ?</rmrsbankitem>
  </proposition>
  <valid id="3.229.a">
    <theory> <ref src="3.229.1"/> </theory>
    <conclusion> <negation> <ref src="3.229.2"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.230">
  <proposition id="3.230.1">
    <rmrsbankitem id="160">ITEL won more orders than APCOM did.</rmrsbankitem>
  </proposition>
  <proposition id="3.230.2">
    <rmrsbankitem id="57">Did ITEL win some orders?</rmrsbankitem>
  </proposition>
  <valid id="3.230.a">
    <theory> <ref src="3.230.1"/> </theory>
    <conclusion> <ref src="3.230.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.231">
  <proposition id="3.231.1">
    <rmrsbankitem id="160">ITEL won more orders than APCOM did.</rmrsbankitem>
  </proposition>
  <proposition id="3.231.2">
    <rmrsbankitem id="58">Did APCOM win some orders?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.231.a">
    <theory> <ref src="3.231.1"/> </theory>
    <conclusion> <ref src="3.231.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.231.a">
    <theory> <ref src="3.231.1"/> </theory>
    <conclusion> <negation> <ref src="3.231.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.232">
  <proposition id="3.232.1">
    <rmrsbankitem id="160">ITEL won more orders than APCOM did.</rmrsbankitem>
  </proposition>
  <proposition id="3.232.2">
    <rmrsbankitem id="16">APCOM won ten orders.</rmrsbankitem>
  </proposition>
  <proposition id="3.232.3">
    <rmrsbankitem id="161">Did ITEL win at least eleven orders?</rmrsbankitem>
  </proposition>
  <valid id="3.232.a">
    <theory> <ref src="3.232.1"/> <ref src="3.232.2"/> </theory>
    <conclusion> <ref src="3.232.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.233">
  <proposition id="3.233.1">
    <rmrsbankitem id="100">ITEL won more orders than APCOM.</rmrsbankitem>
  </proposition>
  <proposition id="3.233.2">
    <rmrsbankitem id="57">Did ITEL win some orders?</rmrsbankitem>
  </proposition>
  <valid id="3.233.a">
    <theory> <ref src="3.233.1"/> </theory>
    <conclusion> <ref src="3.233.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.234">
  <proposition id="3.234.1">
    <rmrsbankitem id="100">ITEL won more orders than APCOM.</rmrsbankitem>
  </proposition>
  <proposition id="3.234.2">
    <rmrsbankitem id="58">Did APCOM win some orders?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.234.a">
    <theory> <ref src="3.234.1"/> </theory>
    <conclusion> <ref src="3.234.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.234.b">
    <theory> <ref src="3.234.1"/> </theory>
    <conclusion> <negation> <ref src="3.234.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.235">
  <proposition id="3.235.1">
    <rmrsbankitem id="100">ITEL won more orders than APCOM.</rmrsbankitem>
  </proposition>
  <proposition id="3.235.2">
    <rmrsbankitem id="16">APCOM won ten orders.</rmrsbankitem>
  </proposition>
  <proposition id="3.235.3">
    <rmrsbankitem id="161">Did ITEL win at least eleven orders?</rmrsbankitem>
  </proposition>
  <valid id="3.235.a">
    <theory> <ref src="3.235.1"/> <ref src="3.235.2"/> </theory>
    <conclusion> <ref src="3.235.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.237">
  <proposition id="3.237.1">
    <rmrsbankitem id="210">ITEL won more orders than the APCOM contract.</rmrsbankitem>
  </proposition>
  <proposition id="3.237.2">
    <rmrsbankitem id="162">Did ITEL win more than one order?</rmrsbankitem>
  </proposition>
  <valid id="3.237.a">
    <theory> <ref src="3.237.1"/> </theory>
    <conclusion> <ref src="3.237.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.238">
  <!-- ITEL won twice as many orders than APCOM. -->
  <proposition id="3.238.1">
    <rmrsbankitem id="211">ITEL won twice as many orders as APCOM.</rmrsbankitem>
  </proposition>
  <proposition id="3.238.2">
    <rmrsbankitem id="16">APCOM won ten orders.</rmrsbankitem>
  </proposition>
  <proposition id="3.238.3">
    <rmrsbankitem id="59">Did ITEL win twenty orders?</rmrsbankitem>
  </proposition>
  <valid id="3.238.a">
    <theory> <ref src="3.238.1"/> <ref src="3.238.2"/> </theory>
    <conclusion> <ref src="3.238.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-2-6.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="2.6" name="collective and distributive plurals">

<testcase id="3.111">
  <proposition id="3.111.1">
    <rmrsbankitem id="6">Smith signed one contract.</rmrsbankitem>
  </proposition>
  <proposition id="3.111.2">
    <rmrsbankitem id="7">Jones signed another contract.</rmrsbankitem>
  </proposition>
  <proposition id="3.111.3">
    <rmrsbankitem id="151">Did Smith and Jones sign two contracts?</rmrsbankitem>
  </proposition>
  <valid id="3.111.a">
    <theory> <ref src="3.111.1"/> <ref src="3.111.2"/> </theory>
    <conclusion> <ref src="3.111.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.112">
  <proposition id="3.112.1">
    <rmrsbankitem id="8">Smith signed two contracts.</rmrsbankitem>
  </proposition>
  <proposition id="3.112.2">
    <rmrsbankitem id="9">Jones signed two contracts.</rmrsbankitem>
  </proposition>
  <proposition id="3.112.3">
    <rmrsbankitem id="151">Did Smith and Jones sign two contracts?</rmrsbankitem>
  </proposition>
  <valid id="3.112.a">
    <theory> <ref src="3.112.1"/> <ref src="3.112.2"/> </theory>
    <conclusion> <ref src="3.112.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.113">
  <proposition id="3.113.1">
    <rmrsbankitem id="8">Smith signed two contracts.</rmrsbankitem>
  </proposition>
  <proposition id="3.113.2">
    <rmrsbankitem id="10">Jones also signed them.</rmrsbankitem>
  </proposition>
  <proposition id="3.113.3">
    <rmrsbankitem id="151">Did Smith and Jones sign two contracts?</rmrsbankitem>
  </proposition>
  <valid id="3.113.a">
    <theory> <ref src="3.113.1"/> <ref src="3.113.2"/> </theory>
    <conclusion> <ref src="3.113.3"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-6-5.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="6.5" name="attributive comparatives">

<testcase id="3.244">
  <proposition id="3.244.1">
    <rmrsbankitem id="212">APCOM has a more important customer than ITEL.</rmrsbankitem>
  </proposition>
  <proposition id="3.244.2">
    <rmrsbankitem id="273">Does APCOM have a more important customer than ITEL is?</rmrsbankitem>
  </proposition>
  <valid id="3.244.a">
    <theory> <ref src="3.244.1"/> </theory>
    <conclusion> <ref src="3.244.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.245">
  <proposition id="3.245.1">
    <rmrsbankitem id="212">APCOM has a more important customer than ITEL.</rmrsbankitem>
  </proposition>
  <proposition id="3.245.2">
    
    <rmrsbankitem id="274">Does APCOM have a more important customer than ITEL has?</rmrsbankitem>
  </proposition>
  <valid id="3.245.a">
    <theory> <ref src="3.245.1"/> </theory>
    <conclusion> <ref src="3.245.2"/> </conclusion>
  </valid>
</testcase>

</testsuite>

=== rbergmair/PyPES/testdta/processed/fracas/fracas-1-1.ts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsuite SYSTEM "file:///home/rb432/workspace/rte/dtd/testsuite.dtd">

<testsuite id="1.1" name="conservativity">

<testcase id="3.1">
  <proposition id="3.1.1">
    <rmrsbankitem id="109">An Italian became the world's greatest tenor.</rmrsbankitem>
  </proposition>
  <proposition id="3.1.2">
    <rmrsbankitem id="250">Was there an Italian who became the world's greatest tenor?</rmrsbankitem>
  </proposition>
  <valid id="3.1.a">
    <theory> <ref src="3.1.1"/> </theory>
    <conclusion> <ref src="3.1.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.2">
  <proposition id="3.2.1">
    <rmrsbankitem id="222">Every Italian man wants to be a great tenor.</rmrsbankitem>
  </proposition>
  <proposition id="3.2.2">
    <rmrsbankitem id="67">Some Italian men are great tenors.</rmrsbankitem>
  </proposition>
  <proposition id="3.2.3">
    <rmrsbankitem id="287">Are there Italian men who want to be a great tenor?</rmrsbankitem>
  </proposition>
  <valid id="3.2.a">
    <theory> <ref src="3.2.1"/> <ref src="3.2.2"/> </theory>
    <conclusion> <ref src="3.2.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.3">
  <proposition id="3.3.1">
    <rmrsbankitem id="223">All Italian men want to be a great tenor.</rmrsbankitem>
  </proposition>
  <proposition id="3.3.2">
    <rmrsbankitem id="67">Some Italian men are great tenors.</rmrsbankitem>
  </proposition>
  <proposition id="3.3.3">
    <rmrsbankitem id="287">Are there Italian men who want to be a great tenor?</rmrsbankitem>
  </proposition>
  <valid id="3.3.a">
    <theory> <ref src="3.3.1"/> <ref src="3.3.2"/> </theory>
    <conclusion> <ref src="3.3.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.4">
  <proposition id="3.4.1">
    <rmrsbankitem id="110">Each Italian tenor wants to be great.</rmrsbankitem>
  </proposition>
  <proposition id="3.4.2">
    <rmrsbankitem id="18">Some Italian tenors are great.</rmrsbankitem>
  </proposition>
  <proposition id="3.4.3">
    <rmrsbankitem id="224">Are there Italian tenors who want to be great?</rmrsbankitem>
  </proposition>
  <valid id="3.4.a">
    <theory> <ref src="3.4.1"/> <ref src="3.4.2"/> </theory>
    <conclusion> <ref src="3.4.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.5">
  <proposition id="3.5.1">
    <rmrsbankitem id="68">The really ambitious tenors are Italian.</rmrsbankitem>
  </proposition>
  <proposition id="3.5.2">
    <rmrsbankitem id="172">Are there really ambitious tenors who are Italian?</rmrsbankitem>
  </proposition>
  <valid id="3.5.a">
    <theory> <ref src="3.5.1"/> </theory>
    <conclusion> <ref src="3.5.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.6">
  <proposition id="3.6.1">
    <rmrsbankitem id="69">No really great tenors are modest.</rmrsbankitem>
  </proposition>
  <proposition id="3.6.2">
    <rmrsbankitem id="173">Are there really great tenors who are modest?</rmrsbankitem>
  </proposition>
  <valid id="3.6.a">
    <theory> <ref src="3.6.1"/> </theory>
    <conclusion> <negation> <ref src="3.6.2"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.7">
  <proposition id="3.7.1">
    <rmrsbankitem id="19">Some great tenors are Swedish.</rmrsbankitem>
  </proposition>
  <proposition id="3.7.2">
    <rmrsbankitem id="111">Are there great tenors who are Swedish?</rmrsbankitem>
  </proposition>
  <valid id="3.7.a">
    <theory> <ref src="3.7.1"/> </theory>
    <conclusion> <ref src="3.7.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.8">
  <proposition id="3.8.1">
    <rmrsbankitem id="20">Many great tenors are German.</rmrsbankitem>
  </proposition>
  <proposition id="3.8.2">
    <rmrsbankitem id="112">Are there great tenors who are German?</rmrsbankitem>
  </proposition>
  <valid id="3.8.a">
    <theory> <ref src="3.8.1"/> </theory>
    <conclusion> <ref src="3.8.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.9">
  <proposition id="3.9.1">
    <rmrsbankitem id="21">Several great tenors are British.</rmrsbankitem>
  </proposition>
  <proposition id="3.9.2">
    <rmrsbankitem id="113">Are there great tenors who are British?</rmrsbankitem>
  </proposition>
  <valid id="3.9.a">
    <theory> <ref src="3.9.1"/> </theory>
    <conclusion> <ref src="3.9.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.10">
  <proposition id="3.10.1">
    <rmrsbankitem id="22">Most great tenors are Italian.</rmrsbankitem>
  </proposition>
  <proposition id="3.10.2">
    <rmrsbankitem id="114">Are there great tenors who are Italian?</rmrsbankitem>
  </proposition>
  <valid id="3.10.a">
    <theory> <ref src="3.10.1"/> </theory>
    <conclusion> <ref src="3.10.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.11">
  <proposition id="3.11.1">
    <rmrsbankitem id="115">A few great tenors sing popular music.</rmrsbankitem>
  </proposition>
  <proposition id="3.11.2">
    <rmrsbankitem id="70">Some great tenors like popular music.</rmrsbankitem>
  </proposition>
  <proposition id="3.11.3">
    <rmrsbankitem id="174">Are there great tenors who sing popular music?</rmrsbankitem>
  </proposition>
  <valid id="3.11.a">
    <theory> <ref src="3.11.1"/> <ref src="3.11.2"/> </theory>
    <conclusion> <ref src="3.11.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.12">
  <proposition id="3.12.1">
    <rmrsbankitem id="23">Few great tenors are poor.</rmrsbankitem>
  </proposition>
  <proposition id="3.12.2">
    <rmrsbankitem id="116">Are there great tenors who are poor?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.12.a">
    <theory> <ref src="3.12.1"/> </theory>
    <conclusion> <ref src="3.12.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.12.b">
    <theory> <ref src="3.12.1"/> </theory>
    <conclusion> <negation> <ref src="3.12.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

<testcase id="3.13">
  <proposition id="3.13.1">
    <rmrsbankitem id="24">Both leading tenors are excellent.</rmrsbankitem>
  </proposition>
  <proposition id="3.13.2">
    <rmrsbankitem id="117">Leading tenors who are excellent are indispensable.</rmrsbankitem>
  </proposition>
  <proposition id="3.13.3">
    <rmrsbankitem id="25">Are both leading tenors indispensable?</rmrsbankitem>
  </proposition>
  <valid id="3.13.a">
    <theory> <ref src="3.13.1"/> <ref src="3.13.2"/> </theory>
    <conclusion> <ref src="3.13.3"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.14">
  <proposition id="3.14.1">
    <rmrsbankitem id="26">Neither leading tenor comes cheap.</rmrsbankitem>
  </proposition>
  <proposition id="3.14.2">
    <rmrsbankitem id="118">One of the leading tenors is Pavarotti.</rmrsbankitem>
  </proposition>
  <proposition id="3.14.3">
    <rmrsbankitem id="175">Is Pavarotti a leading tenor who comes cheap?</rmrsbankitem>
  </proposition>
  <valid id="3.14.a">
    <theory> <ref src="3.14.1"/> <ref src="3.14.2"/> </theory>
    <conclusion> <negation> <ref src="3.14.3"/> </negation> </conclusion>
  </valid>
</testcase>

<testcase id="3.15">
  <proposition id="3.15.1">
    <rmrsbankitem id="251">At least three tenors will take part in the concert.</rmrsbankitem>
  </proposition>
  <proposition id="3.15.2">
    <rmrsbankitem id="252">Are there tenors who will take part in the concert?</rmrsbankitem>
  </proposition>
  <valid id="3.15.a">
    <theory> <ref src="3.15.1"/> </theory>
    <conclusion> <ref src="3.15.2"/> </conclusion>
  </valid>
</testcase>

<testcase id="3.16">
  <proposition id="3.16.1">
    <rmrsbankitem id="253">At most two tenors will contribute their fees to charity.</rmrsbankitem>
  </proposition>
  <proposition id="3.16.2">
    <rmrsbankitem id="254">Are there tenors who will contribute their fees to charity?</rmrsbankitem>
  </proposition>
  <nonvalid id="3.16.a">
    <theory> <ref src="3.16.1"/> </theory>
    <conclusion> <ref src="3.16.2"/> </conclusion>
  </nonvalid>
  <nonvalid id="3.16.b">
    <theory> <ref src="3.16.1"/> </theory>
    <conclusion> <negation> <ref src="3.16.2"/> </negation> </conclusion>
  </nonvalid>
</testcase>

</testsuite>
